### ISSUE TITLE
misc issues

### ISSUE THREAD

**Issue by timotheecour** [timotheecour/Nim#6]
- [ ] `registerSignalHandler` uses signal instead of recommended sigation

**Comment by timotheecour** [comment]
* document that `writeFile` follows symlinks

**Comment by timotheecour** [comment]
`-d:release:off` doesn't unset `-d:release` ; WORKAROUND: use `-u:release`

**Comment by timotheecour** [comment]
- [x] walkDir + friends should throw if input path doesn't exist/invalid etc
refs: https://github.com/nim-lang/Nim/pull/13163

EDIT: fixed in https://github.com/nim-lang/Nim/pull/13642 (via checkDir option)

**Comment by timotheecour** [comment]
```
proc toDll*(filename: string): string =
  ## On Windows adds ".dll" to `filename`, on Posix produces "lib$filename.so".
  (when defined(windows): filename & ".dll" else: "lib" & filename & ".so")
```
=> OSX??

**Comment by timotheecour** [comment]
- [x] nimscript:
exception handling doesn't support `Exception as e`
```nim
try: foo
except Exception as e: bar
``
nor getCurrentException, nor getCurrentExceptionMsg

Edited:
Itt works now
`nim e --eval:"try: echo 1 except Exception as e: echo 2"`
prints: 1

**Comment by timotheecour** [comment]
adding `--passc:-flto` does not recompile C sources; need `-f` workaround

**Comment by timotheecour** [comment]
- [ ] => https://github.com/timotheecour/Nim/issues/200

**Comment by timotheecour** [comment]
* maybe we should add a timeout for individual tests to avoid problems like this in future (rest of tests will run ; at least we'll know which test(s) timeout instead of just travis timing out w no diagnostic info)

**Comment by timotheecour** [comment]
line tracing doesn't help here:

```
--embedsrc
--linetrace:on
--linedir
```

```
nimb cpp -r -f -d:case1 --stacktrace:on --passc:-D=NIM_ENABLE_BACKEND_WARNING --passC:'-Wwrite-strings -Wno-tautological-constant-out-of-range-compare -Wno-incompatible-pointer-types-discards-qualifiers -Wno-writable-strings -Wno-invalid-offsetof' --embedsrc --hint:cc:on --linetrace:on --linedir compiler/btrees.nim
```

```
#line 159 "/Users/timothee/git_clone/nim/Nim_prs/compiler/btrees.nim"
	unsureAsgnRef((void**) (&(*Result).Field0), copyString(colontmp_));	unsureAsgnRef((void**) (&(*Result).Field1), copyString(colontmp__2));	(*Result).Field2 = colontmp__3;	popFrame();}
static N_NIMCALL(void, Marker_tyRef__IL7aN7O9aNru9bTSC89c5Ikqw)(void* p, NI op) {
	tyObject_NodecolonObjectType___N9cnVBw3Vb4RjTWgNwB6wqw* a;
	NI T1_;	NI T2_;	NI T3_;	a = (tyObject_NodecolonObjectType___N9cnVBw3Vb4RjTWgNwB6wqw*)p;
	T1_ = (NI)0;	switch ((*a).isInternal) {
	case NIM_FALSE:
	T2_ = (NI)0;	for (T2_ = 0; T2_ < 512; T2_++) {	nimGCvisit((void*)(*a)._isInternal_1.vals[T2_], op);	}
	break;
	case NIM_TRUE:
	T3_ = (NI)0;	for (T3_ = 0; T3_ < 512; T3_++) {	nimGCvisit((void*)(*a)._isInternal_2.links[T3_], op);	}
	break;
	} 
}
```

for this code:
```
proc next*[Key, Val](b: BTree[Key, Val]; index: int): (Key, Val, int) =
  var it = b.root
  var i = index
  # navigate to the right leaf:
  while it.isInternal:
    var sum = 0
    for k in 0..<it.entries:
      let c = countSubTree(it.links[k])
      inc sum, c
      if sum > i:
        it = it.links[k]
        dec i, (sum - c)
        break
  result = (it.keys[i], it.vals[i], index+1)
```

**Comment by timotheecour** [comment]
```
#    /* consider using NULL if comment below for NIM_NIL doesn't apply to C++ */
#    define NIM_NIL 0
```
indeed https://stackoverflow.com/a/50766105/1426932
[ Note: In particular, neither the null pointer conversion for a zero-valued integral constant expression ([conv.ptr]) nor the derived-to-base conversion ([conv.ptr]) are applied. Although 0 is a valid template-argument for a non-type template-parameter of integral type, it is not a valid template-argument for a non-type template-parameter of pointer type. However, both (int*)0 and nullptr are valid template-arguments for a non-type template-parameter of type “pointer to int.” — end note ]

**Comment by timotheecour** [comment]
wrong error message in sigmatch: 
should show `int` instead of `range 0..512(int)`
```nim
proc bar(a: csize_t) = discard

proc fun[R](a: array[R, char]) =
  const N = high(a)
  static: doAssert N is int
  bar(N)

var a: array[0..512, char]
fun(a)
```

```
Error: type mismatch: got <range 0..512(int)>
but expected one of:
proc bar(a: csize_t)
  first type mismatch at position: 1
  required type for a: csize_t
  but expression 'N' is of type: range 0..512(int)

expression: bar(N)
    bar(N)
```

**Comment by timotheecour** [comment]
freebsd BUG getApplFreebsd

https://github.com/nim-lang/Nim/pull/12179/files#r399875661

**Comment by timotheecour** [comment]
track https://github.com/nim-lang/Nim/pull/13665 
Add 2 new modules, xpm.nim and netpbm.nim.
=> nimble package?

**Comment by timotheecour** [comment]
track `isSsd` https://github.com/nim-lang/Nim/pull/13533

**Comment by timotheecour** [comment]
track  [Documentation async by juancarlospaco · Pull Request #12979 · nim-lang/Nim : Documentation async by juancarlospaco · Pull Request #12979 · nim-lang/Nim](https://github.com/nim-lang/Nim/pull/12979)
> So, if we all agree on that, can we close this PR and use its content as a basis for doc/tut4.rst, which will be async tutorial?

**Comment by timotheecour** [comment]
track:
* [Add jsformdata by juancarlospaco · Pull Request #12451 · nim-lang/Nim : Add jsformdata by juancarlospaco · Pull Request #12451 · nim-lang/Nim](https://github.com/nim-lang/Nim/pull/12451)
* [Add mathconstants to std lib by juancarlospaco · Pull Request #12123 · nim-lang/Nim : Add mathconstants to std lib by juancarlospaco · Pull Request #12123 · nim-lang/Nim](https://github.com/nim-lang/Nim/pull/12123)
* `isSsd` https://github.com/nim-lang/Nim/pull/13533
* https://github.com/nim-lang/Nim/pull/13665  Add 2 new modules, xpm.nim and netpbm.nim. => nimble package?

**Comment by timotheecour** [comment]
* track https://github.com/nim-lang/Nim/pull/13803#issuecomment-606354919 Faster CIs
* check https://github.com/nim-lang/Nim/pull/13803/files
re-instigate this test: https://github.com/nim-lang/Nim/pull/13803/commits/a60cc28239161883d28491f401ae584b545b6c0c tindexerrorformatbounds and merge it to tests/trunner
* 
``
  when defined(posix):	
      kochExecFold("Docs", "docs --git.commit:devel")	
      kochExecFold("C sources", "csource")
  elif defined(windows):	
      when false:	
        kochExec "csource"	
        kochExec "zip"	
```

* maybe we need: `nim runExamples main.nim`

* 
> we don't bootstrap without -d:release anymore (-d:release is not as dangerous as before, we have -d:danger now); csources are now archived, no need to run kochExecFold("C sources", "csource") anymore

=> but doesn't mean we shouldn't test the code that runs csource, that code could regress; we ARE gonna need to rebuild csources at some point even if csources is frozen, to avoid keeping having to bootstrap from a really old compiler (so we can simplify nim code)

> added Github workflow for checking if the documentation is still correct, no need to run kochExecFold("Docs", "docs --git.commit:devel") anymore on every PR

=> but now, `nim doc` only run from ubuntu; sometimes, these are our only tests

* remove 'gc:none' and 'refc' without 'd:useRealtimeGC' from gc tests

**Comment by timotheecour** [comment]
csources not being tested anymore
> csources are now archived, no need to run kochExecFold("C sources", "csource") anymore

https://github.com/nim-lang/Nim/pull/13803#issuecomment-606354919

**Comment by timotheecour** [comment]
* D20200331T022512 features need to be localizable in VM (just like in non vm code)
eg: this should work
```
{.push experimental: Foo.}
bar()
{.pop.}
```

**Comment by timotheecour** [comment]
deprecate `isNil(a: IntSet)` since IntSet is an object; maybe use same treatment as isNil for string etc (user defined error)

**Comment by timotheecour** [comment]
- [ ] track https://github.com/nim-lang/Nim/issues/6638#issuecomment-606943077 not nil

Edited:
null safe make some progresses now
https://nim-lang.github.io/Nim/manual_experimental_strictnotnil.html

**Comment by timotheecour** [comment]
- [x] `defined(macos)` is often wrong eg shd be `defined(osx)`
eg: `openDefaultBrowser` fails on OSX

also, check whether https://github.com/nim-lang/Nim/pull/13818 is desirable on osx, or whether it prevents useful case of just opening browser

pending https://github.com/nim-lang/Nim/pull/13892

**Comment by timotheecour** [comment]
- [x] track my feedback for https://github.com/nim-lang/Nim/pull/13811 (eg https://github.com/nim-lang/Nim/pull/13811#discussion_r401291562)

**Comment by timotheecour** [comment]
https://github.com/nim-lang/Nim/pull/13809#discussion_r401287070
> what about tools/dochack which includes tools/dochack/dochack.nim?

**Comment by timotheecour** [comment]
- [ ] reenable `nim doc` for compiler sources (see https://github.com/nim-lang/Nim/pull/13221) after some of the stuff was undone; note: requires also checking that the new github actions triggers on those sources too

**Comment by timotheecour** [comment]
- [x] track: https://github.com/nim-lang/Nim/pull/13808#discussion_r401327323
avoid performance regression

**Comment by timotheecour** [comment]
- [x] track https://github.com/nim-lang/Nim/pull/12448#discussion_r401977012

**Comment by timotheecour** [comment]
- [x] track https://github.com/nim-lang/Nim/pull/13844#issuecomment-607744008 std/byaddr

**Comment by timotheecour** [comment]
- [ ] track https://github.com/nim-lang/Nim/commit/8ee0771b5a10cfd083ba2eba806e5d9d9f72b234#commitcomment-38239130
Natural return type

**Comment by timotheecour** [comment]
- [ ] `{.push ignoreNotNil.}` to allow ignoring `not nil` in a scope, eg for `seq.setLen`

**Comment by timotheecour** [comment]
- [ ] fix [nimbase.h not copied with --genScript in devel (works in 1.0.6) · Issue #13826 · nim-lang/Nim : nimbase.h not copied with --genScript in devel (works in 1.0.6) · Issue #13826 · nim-lang/Nim](https://github.com/nim-lang/Nim/issues/13826)

using this:

> nimbase.h should be tracked as a depdendency in the main.json file generated by --genscript and maybe also the generated main.deps file

**Comment by timotheecour** [comment]
- [x] [`nimgrep --nocolor` is ignored on posix; should be instead: `--nimgrep --color=[auto]|true|false` · Issue #7591 · nim-lang/Nim : `nimgrep --nocolor` is ignored on posix; should be instead: `--nimgrep --color=[auto]|true|false` · Issue #7591 · nim-lang/Nim](https://github.com/nim-lang/Nim/issues/7591)

**Comment by timotheecour** [comment]
D20200405T131708 
macro pragma not overloadable
```nim
macro bar(body): untyped =
  body

template bar(a: int, b: string): untyped =
  discard

proc fun(a: int) {.bar.} =
  discard

```

and errmsg is bad:
Error: redefinition of 'fun'; previous declaration here: /Users/timothee/git_clone/nim/timn/tests/nim/all/t10503.nim(11, 6)
  proc fun(a: int) {.bar.} =
  ^

**Comment by timotheecour** [comment]
show resolved types in errmsgs
instead of useless:
```nim
but expected one of:
proc contains[T](x: set[T]; y: T): bool
  first type mismatch at position: 2
  required type for y: T
  but expression 'sfVarPragma' is of type: TSymFlag
6 other mismatching symbols have been suppressed; compile with --showAllMismatches:on to see them

expression: contains(symi.flags, sfVarPragma)
          if sfVarPragma in symi.flags:

```

**Comment by timotheecour** [comment]
check this: `# xxx: also check for nkRefTy as in opcLdDeref?` see https://github.com/nim-lang/Nim/pull/13865/files#diff-df1f02d5585eaaa687dd520ca30be3faR801

**Comment by timotheecour** [comment]
add test case from https://github.com/timotheecour/vitanim/blob/master/testcases/tests/test_vm_var_importc.nim left over from [VM: support importc var, ptr/pointer types, cast int <=> ptr/pointer by timotheecour · Pull Request #12877 · nim-lang/Nim : VM: support importc var, ptr/pointer types, cast int <=> ptr/pointer by timotheecour · Pull Request #12877 · nim-lang/Nim](https://github.com/nim-lang/Nim/pull/12877)

**Comment by timotheecour** [comment]
rebuild logic should check nimbase.h (at least)

**Comment by timotheecour** [comment]
check whether noinit in some parts of stdlib suffer from this:
https://github.com/dlang/phobos/pull/6178#discussion_r178309551
```nim
var a {.noinit.}: seq[Foo]
a.setLenUninitialized(n)
fillUp(a)
```
if `fillUp` throws before `a` was filled up, you may get garbage references that would never be released, causing memory leaks?
which GC's could that affect?
see whether suggestion proposed in that link works

**Comment by timotheecour** [comment]
- [ ] remaining TODO's in [openDefaultBrowser now works on OSX by timotheecour · Pull Request #13892 · nim-lang/Nim : openDefaultBrowser now works on OSX by timotheecour · Pull Request #13892 · nim-lang/Nim](https://github.com/nim-lang/Nim/pull/13892)

**Comment by timotheecour** [comment]
`--hints:off --hint:cc` should work

**Comment by timotheecour** [comment]
nkNilLit shd be in nkLiterals

**Comment by timotheecour** [comment]
callDepthLimitReached should raise StackOverflowError (currently unused)

**Comment by timotheecour** [comment]
fmt:
```fmt"foo{b["title"]}bar"```
Error: could not parse `b[`.

**Comment by timotheecour** [comment]
adding `--hint:cc:on` should imply `-f` but doesnt'

**Comment by timotheecour** [comment]
- [ ] https://github.com/nim-lang/Nim/pull/13919#issuecomment-612037691

> I also added a new define (-d:noOpenSSLHacks)

should be -d:nimNoOpenSSLHacks to avoid name clashes

**Comment by timotheecour** [comment]
https://github.com/status-im/nim-stint/issues/103#issuecomment-612258174
(fix for https://github.com/status-im/nim-stint/issues/103 bundled in pr_misc)

**Comment by timotheecour** [comment]
fix this:
> adding entries should not yield duplicate ABI checks, as enforced by
> `typeABICache`.
> Currently the test doesn't check for this but you can inspect the cgen'd file

in https://github.com/nim-lang/Nim/pull/13926/files

using `c_currentSourcePath ` from https://github.com/nim-lang/Nim/pull/13953
(ie, tell whether ccodegen is correct wrt duplicate static assert checks)

**Comment by timotheecour** [comment]
lhmbp $nim_prs_D br:pr_fix_tnim_88_SIGSEGV_VM  $ $(d_nim_bin).ffi.1 cpp --passC:-std=c++11 -d:timn_D20191207T181719 --app:lib -o:/tmp/libD20191211T004436.dylib $vitanim_D/testcases/tests/test_vm_var_importc_imp.nim

regression test case from test_vm_var_importc_imp.nim should be added to testament, see [VM: support importc var, ptr/pointer types, cast int <=> ptr/pointer by timotheecour · Pull Request #12877 · nim-lang/Nim : VM: support importc var, ptr/pointer types, cast int <=> ptr/pointer by timotheecour · Pull Request #12877 · nim-lang/Nim](https://github.com/nim-lang/Nim/pull/12877)

**Comment by timotheecour** [comment]
nim doesn't understand empty (or whitespace only) args in cmd line:
```
nim c --foo.bar.baz:' ' $timn_D/tests/nim/all/t10552.nim
command line(1, 2) Error: command expects a filename
```

**Comment by timotheecour** [comment]
`C:\Users\timothee\git_clone\Nim>bin\nim_temp1.exe c --cc:vcc --warning:backendwarning:off -f --hint:conf:off tests/misc/mbackendwarnings.nim`

=> `nimbase.h(522): error C2118: negative subscript`
fails ABI test on windows

**Comment by timotheecour** [comment]
Error: VM does not support 'cast' from tyPointer to tyCString

**Comment by timotheecour** [comment]
- [ ] compiler could give a warning or CT error for `var a: MyEnumWithOffset`, eg for DateTime.month, see https://github.com/nim-lang/Nim/pull/14002#issuecomment-615195005 and https://github.com/nim-lang/Nim/pull/14002/files#r410529632

> unlike range[1..31], it's currently legal in Nim and doesn't give any warnings; if it becomes illegal or deprecated, this can be changed

**Comment by timotheecour** [comment]
- [ ] remove unused  NimCompilerApiVersion but how come there r no unused warning? does it not work for const?

**Comment by timotheecour** [comment]
SomeOrdinal should include char, and SomeOrdinal vs Ordinal doc should improve

**Comment by timotheecour** [comment]
in an include file imported from several places, we probably should not generate `XDeclaredButNotUsed`

/Users/timothee/git_clone/nim/Nim_prs/lib/system/inclrtl.nim(54, 10) Hint: 'isSince' is declared but not used [XDeclaredButNotUsed]

**Comment by timotheecour** [comment]
- [x] report the regex bug affecting re and nre (and now, nim-regex) [regression: ^ incorrect when start != 0 · Issue #64 · nitely/nim-regex](https://github.com/nitely/nim-regex/issues/64)
=> done (reported)

**Comment by timotheecour** [comment]
- [x] check whether `nim c -b:cpp main` works

**Comment by timotheecour** [comment]
changelog https://github.com/nim-lang/Nim/pull/14278

**Comment by timotheecour** [comment]
=> [adding `--hint:cc` doesn't trigger a recompilation with nimBetterRun · Issue #257 · timotheecour/Nim](https://github.com/timotheecour/Nim/issues/257)

**Comment by timotheecour** [comment]
https://github.com/nim-lang/Nim/issues/12293#issuecomment-627958077

- [ ] `findNimStdLib` will not work with choosenim-installed nim; this is in part due to choosenim shims (https://github.com/dom96/choosenim/issues/189); it could use `nim dump --dump.format:json` at runtime
- [ ] `nimble install compiler` is misleading and this seems like a bug:
it installs under:
`/Users/timothee/.nimble/pkgs/compiler-1.3.5/compiler.nimble`
yet uses the latest release tag, 1.2, so the 1.3.5 is really misleading

**Comment by timotheecour** [comment]
--parallelBuild:1 disables hintCC

**Comment by timotheecour** [comment]
- [ ] `SomePointer` should include cstring in options.nim

see `pr_typetraits_somePointer` D20210223T123714
blocked by https://github.com/nim-lang/Nim/pull/16026

**Comment by timotheecour** [comment]
create a bugreport for other root cause of #14404 see https://github.com/nim-lang/Nim/pull/14413#issuecomment-632390809

**Comment by timotheecour** [comment]
add test for:
[fix #9227 procs can now have multiple interleaved doc comments + runnableExamples and be docgen'd correctly by timotheecour · Pull Request #14441 · nim-lang/Nim](https://github.com/nim-lang/Nim/pull/14441)

**Comment by timotheecour** [comment]
unittest
```
  template asgn(a: untyped, value: typed) =
    var a = value # XXX: we need "var: var" here in order to
                  # preserve the semantics of var params

```

**Comment by timotheecour** [comment]
backport trailing else
